### ISSUE TITLE
Players joining without DM the combat tracker doesn't get reordered

### ISSUE THREAD

**Issue by Azmoria** [cyruzzo/AboveVTT#1096]
Putting this here as a reminder but if someone else gets to it that's fine.

Reported in discord when joining as a player if the session ended mid combat the combat tracker will be in the wrong order. The combat tracker is currently only reordered by the DM - then synced to the players.

I think we can change it to have players combat trackers also reorder but just have persist = false.

**Comment by Josh-Archer** [comment]
Ill take this one
