### ISSUE TITLE
Temp HP on characters gets added every time a token moves

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#1104]
![gif](https://media.discordapp.net/attachments/815028804103307354/1093542213541187625/AboveVTT-bug-HPIncreaseOnMove.gif)

**Comment by Josh-Archer** [comment]
Is this only for DM, player or both movements?

**Comment by Josh-Archer** [comment]
> Is this only for DM, player or both movements?

Nvm, I found the issue. Ill take this
