### ISSUE TITLE
monster sheet is sometimes blank

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#228]
Haven't been able to reproduce this yet, but [turtle_stew reported it on discord](https://discord.com/channels/815028457851191326/815028804103307354/951247430555406376)

**Comment by bain2236** [comment]
I've had this. I'll try to re-create it

**Comment by cyruzzo** [comment]
I think some small issues happens also when we you switch scene and open a monster sheet too quickly (before the encounter handler finishes fixing up the underlying encounter).
It's probably just a matter of handling the loading phase.
