### ISSUE TITLE
scroll bars cover the dice buttons in the gamelog

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#237]
On Windows, the scroll bars are always present and overlap parts of the UI. As reported by [fizzcannon in Discord](https://discord.com/channels/815028457851191326/815028804103307354/951524782153809990)

**Comment by bain2236** [comment]
Not figured out how I develop against AVTT yet. But adding !important as shown in this snippet works (also flipped the calc around as personally it's more readable)
Additionally, this was not a problem when using stylus extension with the dark mode and the "rest of the DNDB site" styles

![image](https://user-images.githubusercontent.com/9283242/157826865-85bf0d59-d707-4b41-a8e1-f76af70dfb0d.png)

**Comment by bain2236** [comment]
https://github.com/cyruzzo/AboveVTT/pull/242
