### ISSUE TITLE
Firefox specifically, I don't seem to be able to continually draw walls or hold down a key to 'unsnap' tokens

### ISSUE THREAD

**Issue by dubiousgit** [cyruzzo/AboveVTT#2465]
Should it be possible on firefox to continually draw walls (I think it's supposed to be ctrl or shift held down,) and move tokens 'freely' by holding down a hotkey?

I've seen it done in videos, but it doesn't seem to work for the Firefox extension. It's quite possible I'm doing something wrong.

I have tried disabling every extension but AboveVTT but it doesn't seem to make a difference.

**Comment by Azmoria** [comment]
This seems to be working for me. I'm on windows 11 in case it's an OS thing. 

I'm not sure what would cause that - maybe a key stuck down like a fn key or some sort of windows sticky keys settings? Maybe double check firefox is updated in case there's some bug there. Not sure what other trouble shooting steps to take

Holding shift while drawing a wall should allow you to chain it - right click is the other option for this.

You're correct that ctrl should temporarily enabled/disable snap (which ever is the opposite of the current scene settings).


https://github.com/user-attachments/assets/c21e9cb4-e424-4b1b-a16e-c863dcb12f9a

**Comment by dubiousgit** [comment]
Hey @Azmoria thanks for the quick response. 

Since you confirmed it should work, I did some digging; it looks like whatever compilation settings Fedora apply when building Firefox from source, are the factor here. I installed the Flatpak version from Flathub and is appears to be working correctly with that build.

I'll try and track it down with the Fedora people, thanks again for confirming!
