### ISSUE TITLE
Clean up token lock/unlock/restrict player movement

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#256]
Currently, they are two separate options that interact with each other. They could be combined into a single option with 3 states

**Comment by vlaminck** [comment]
We might also want to solve #251 at the same time

**Comment by Azmoria** [comment]
We would be able to condense these somewhat easily now with the new menus. Is this something we still want or is the 'not a token' style taking care of this now? @vlaminck @cyruzzo
