### ISSUE TITLE
Limit token size

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#258]
There should be some upper bound on token sizes. We had a user with performance issues that were cause by a token that was set to 14533333 px

**Comment by RuneKeeperOfTheUr** [comment]
PLEASE FOR THE LOVE OF GOD NO! 

STOP REMOVING FEATURES AND ADDING REALLY CRAPPY LIMITATIONS! First no tokens outside the map and now you're trying to screw over custom token size? HTF are we supposed to run Spelljammer properly if you do that? _**FFS -NO-.**_ This is an AWFUL idea. **PLEASE DO NOT DO THIS.**

**Comment by vlaminck** [comment]
> STOP REMOVING FEATURES AND ADDING REALLY CRAPPY LIMITATIONS! ... _**FFS -NO-.**_ This is an AWFUL idea. **PLEASE DO NOT DO THIS.**

Calm down. There's no need to yell or belittle ideas. 

> First no tokens outside the map...

Tokens can go outside the map, just not as far as they used to. We did this because tokens were getting lost at locations the browser couldn't scroll to. If you can't place tokens outside the map at all, that's a bug. Please raise it as such. If you want to be able to place tokens further off the map, ask for that as a feature request. 

> ... and now you're trying to screw over custom token size?

My understanding is that this ticket is meant to prevent tokens from being excessively larger than the map because that causes performance issues. If you need tokens that are larger than your map, you should consider using that token as the map itself, or change your scale so that your token fits within the map. In your example of Spelljammer, you simply need whatever space-looking image you want for your background, and then use the wizard to make sure your grid size can accommodate large ships. People do it all the time with ships on the ocean, and spelljammer ships are no different. If you need help setting up a map to accommodate large ships, there are a lot of friendly and helpful people in the Discord that can help you.

**Comment by pensan** [comment]
For reference: if we want to allow tokens to move more then '1 grid size' step outside of the scene, there is configuration value to specify it:

`SCENE_MOVE_GRID_PADDING_MULTIPLIER` (https://github.com/cyruzzo/AboveVTT/pull/570/files#diff-ab4097c962c4e0be21f37f7b9beedf07e976bafd4d6c91fcaece8405cfec4096L46)

I assume we could set this to 2 or 3 without causing to much problems.
This would allow tokens to move twice or tribble their size outside of the map.

**Comment by Azmoria** [comment]
Closing this as it has been addressed already in pensans PR above. If necessary we can adjust as they've mentioned but it doesn't seem to be a complaint that comes up.
