### ISSUE TITLE
Ruler improvements

### ISSUE THREAD

**Issue by bain2236** [cyruzzo/AboveVTT#267]
- Text should scale to the users viewport rather than the VTTwrapper size (or whatever it currently scaled to)
- Add math.round as maps that use decimals have rounding issues (eg maps that use 0.1 miles)
- Investigate the ruler waypoint not being applied on first RMB click

https://discord.com/channels/815028457851191326/815028804103307354/953030669817217024

**Comment by vlaminck** [comment]
@Azmoria Does #269 close this issue?

**Comment by Azmoria** [comment]
The scaling and right miuse button should be done. I think the math rounding might need to be checked unless it was caught in another pr.

**Comment by bain2236** [comment]
I've probably still got the branch rocking about for the math rounding so I'll sort that out in the morning

**Comment by Azmoria** [comment]
Ah makes sense must have came from your example and I had forgotten about it.
