### ISSUE TITLE
Allow users to add text to maps

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#315]
As a user, I want to add text labels to my maps similar to how I can add drawings, but without having to hack tokens. 

Ideally, users would be able to set and edit things like 
* font family
* font size
* font color
* stroke width
* stroke color
* text alignment
* background color
* map position

Fine tuning the value and position of a text label will be important.

**Comment by bain2236** [comment]
Hopefully a task list works within the comments, This will be a live comment as I update things
From original requirements
- [x] font family
- [x] font size
- [x] font colour 
- [x] stroke width
- [x] stroke color
- [x] text alignment
- [x] background colour
- [x] map position 
- [x] persist drawn text

- [ ] double check fonts are browser safe
- [ ] fix spacing issue (possibly move to monospaced fonts)
- [ ] allow text box to expand as you type and not suddenly minimize
- [ ] possibly change "enter" key to submit and add a submit button instead
- [ ] move location of colour picker
- [ ] allow multiline content 
- [ ] final once over of code, add jsdocs, remove dodgy comments etc
- [ ] another pass at trying to make dragging box not janky
