### ISSUE TITLE
Changing "Send To" in the gamelog doesn't sync to monster stat blocks.

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#330]
Changing the `Send To (Default)` in the gamelog should also change it in the monster stat blocks. This is done in the `sync_send_to_default` function in `EncounterHandler`, but apparently isn't working all the time.

Reported by [invictus92 on Discord](https://discord.com/channels/815028457851191326/815028804103307354/956139147351982080)

**Comment by Azmoria** [comment]
Only thing I could reproduce with this is opening a monster it seems to default to self after 1 roll for me. After that I can swap the `send to` menu back and forth and it will work sending to everyone again. This only lasts until I click `Character Sheet` for a monster(same or different) in the context menu or combat log.
