### ISSUE TITLE
Allow DM to override AC of monsters

### ISSUE THREAD

**Issue by bain2236** [cyruzzo/AboveVTT#335]
Currently there's no way to handle a monster casting mage armour or the like.
mentioned [here](https://discord.com/channels/815028457851191326/815028716040224818/956096945380818994)
Also see Stumpies message below in overriding rather than adding conditions etc

**Comment by vlaminck** [comment]
This already exists. It was introduced here https://github.com/cyruzzo/AboveVTT/pull/161

**Comment by bain2236** [comment]
ha!, @Azmoria is just too fast!

**Comment by bain2236** [comment]
ahh! I didn't realise it was in the context menu
