### ISSUE TITLE
Hide token aura's when token is hidden

### ISSUE THREAD

**Issue by bain2236** [cyruzzo/AboveVTT#343]
didn't realise this was a thing until someone mentioned it and I checked.
I ran an entire session following the players with a "sound token" to gauge when I should ask for stealth checks..
they didn't mention it to me.

**Comment by StumpyScot** [comment]
I'm sure this can be closed now. @bain2236 can you confirm and close this if I am right?

**Comment by bain2236** [comment]
PR is sat waiting for the big green tick
