### ISSUE TITLE
Add "Join AboveVTT" button to the encounters page

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#352]
As a DM, it would be convenient to be able to start the AboveVTT session from a specific encounter.

This requires https://github.com/cyruzzo/AboveVTT/issues/297 to be completed first.

**Comment by vlaminck** [comment]
Closing this for the same reasons as #300. Maybe some day we'll come back to these, but for now we are not considering this.

**Comment by vlaminck** [comment]
In order for this to work, we need to stop using the campaign join link for cloud interactions. My understanding is that we don't want to just use the `campaignId` because it's a sequential id. Therefore, we need to come up with a unique identifier for a campaign that can't be easily figured out. One suggestion that I've heard is to use a hash of the campaign id and the campaign creation date. We already fetch this information on the encounters page, but we'd have to start fetching it from the characters page as well. The hard part would be migrating the cloud to use this new key instead of the old one.

**Comment by cyruzzo** [comment]
we probably don't need to have this in the encounter page.  surely not in 1.0
