### ISSUE TITLE
The restrictTokenMovement setting should not apply to players that own their own tokens

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#363]
This needs to be figured out in a way that makes the most sense. It technically works as intended, but the behavior is not desired. If a DM sets the global setting, they have to disable it on every player token that is placed. 

1. We could ignore the setting for players trying to move their own token. 
2. We could ignore the setting when placing player tokens.
3. We could add another global setting to ignore restrictTokenMovement for player tokens (this could need special UI since it’s dependent upon the original). 
4. Some other solution. Add a comment if you have other ideas for gore to handle this

**Comment by vlaminck** [comment]
I think option 1 is the best solution, but recognize that it goes against the meaning of the setting

**Comment by vlaminck** [comment]
A lot of good points there, and I think that's actually a new option that I hadn't considered. I was thinking that restrictPlayerMovement would still apply to player tokens, but the owner of the token would ignore it. So PlayerA could move TokenA, but not TokenB. Similarly, PlayerB could move TokenB, but not TokenA.

What you're describing is to fundamentally separate player tokens from all other tokens (as far as global settings are concerned). I'll update the comment to include that as an option

**Comment by bain2236** [comment]
the new 1 seems like the best approach now 🤘
