### ISSUE TITLE
Bottom of "Game Log" cut off in Chrome

### ISSUE THREAD

**Issue by cyruzzo** [cyruzzo/AboveVTT#442]
There has been this report on the DDB forums:

![image](https://user-images.githubusercontent.com/80426829/165564383-871949f1-e7fc-4128-ab3b-ec86190b0f5a.png)

**Comment by bain2236** [comment]
Spotted this the other day but didn't put 2+2 together and thought it was a DNDB issue. 
![image](https://user-images.githubusercontent.com/9283242/165565635-7b831177-6b5e-48e3-a16e-21c19207230a.png)
