### ISSUE TITLE
grid snapping not working on a new scene (need to be confirmed)

### ISSUE THREAD

**Issue by cyruzzo** [cyruzzo/AboveVTT#504]
USER REPORT:

Just noticed something weird in setting up a scene. I created a new scene, pasted the map link, ensured snap to grid was on then ran super mega wizard. I chose "Align to Grid" as my map is pre-gridded, pressed finish, set the grid to 5 ft squares. It dropped me to the map, so I placed my players tokens. They are the right size, but they're not snapping to the grid, so I ran the wizard again, this time the tokens disappeared when the wizard was done. I drug one token back out manually and it wouldn't snap to grid. I moved to a different scene, then came back, all tokens were back on the map and snapping is working... any thoughts? (modificato)

So I tried this again, making a second scene, following all the steps I did the first time, but making sure to click the "DM" button again before placing tokens. The tokens still wouldn't snap to grid until I toggled the "snap to grid" to off, back to on, then clicked the button.

**Comment by bain2236** [comment]
Setting snap/show grid and then running the super wizard doesn't then save the form data when the wizard finishes so snap/grid will go back to the default of being off.

I've also noticed that there's another issue with snapping that appears to cause the "tokens flying off into white space" issue
reproduction steps

1. Create scene,
2. add map to scene
3. super wizard to align map. 
4. Add token (no snapping) move it around and it's fine.
5. edit scene, toggle snapping.
6. Move token, it snaps as expected.
7. Hit save, move token, token flies off.
