### ISSUE TITLE
Custom encounter token options not working after switching scene

### ISSUE THREAD

**Issue by pensan** [cyruzzo/AboveVTT#617]
Reported by Seraphim in Discord (https://discord.com/channels/815028457851191326/815028804103307354/999721956465192970)

When creating a custom encounter on DnDbeyond, token options (gear icon) are only accessible when the current scene is directly loaded.

Switching to another scene results in the following error:

![image](https://user-images.githubusercontent.com/687121/180274527-fb67ec98-3f26-4d9e-92ac-f3e02605437b.png)

Workaround: Reloading the window will fix the problem

**Comment by Seraphim54** [comment]
I would also add that the error only occurs when attempting to use entries 2-? - entry 1 under the encounter (the Scholarly Agent) still worked post scene swap.
