### ISSUE TITLE
Request: Popout functionality

### ISSUE THREAD

**Issue by Azmoria** [cyruzzo/AboveVTT#630]
@Cyruzzo how do you feel about popout functionality for post v1.0 or sooner if it is done? Here's a rough example: https://www.youtube.com/watch?v=QPtsMYlJ1vg

If Cyruzzo approves this. Below is the functions I was using if someone wants to take it and build on it. I haven't made any UI for it yet.

Suggested places to have popouts:

• ~~Monster stat blocks~~ Edit: This has been done
• Some of the side panels (journal, sound etc)?
• Combat tracker?

I'm unsure if we can get this to work for the gamelog or player sheets due to us not building the roll buttons and some other stuff. This should be a good starting point for the rest though.

Edit: Mock up UI popout button for Monsters example https://www.youtube.com/watch?v=inxNJTOt7VU
```
var childWindows = {};

function popoutWindow(name, cloneSelector){
	// use a unique name for windows you want to open seperately. If you want to override an open window use the same name.
	const params = `scrollbars=no,resizable=yes,status=no,location=no,toolbar=no,menubar=no,
width=400,height=800,left=100,top=100`;
	childWindows[name] = window.open(``, name, params);		
	childWindows[name].onbeforeunload = function(){ 
		closePopout(name);
	}
	$(childWindows[name].document).find('body, head').empty();
	$(childWindows[name].document).find('body').append(cloneSelector.clone(true,true));
	$(childWindows[name].document).find('head').append($('link, style').clone());
	return childWindows[name];
}

function closePopout(name){
	if(childWindows[name]){
		childWindows[name].close();
		delete childWindows[name];
	}
}
```

**Comment by cyruzzo** [comment]
it's probably useful for people with big/multiple screens... as long you don't go mich around the code changing how the current pieces are built.. it's ok to have it once it's ready

**Comment by Azmoria** [comment]
I think most of the big things have been covered here for my request. Can reopen/create a new issue if we want other popouts of existing items.
