### ISSUE TITLE
Add a "previous" button to the combat tracker

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#742]
Similar to the "next" button that already exists, but allows the DM to move the combat tracker turn back one. If the DM accidentally moves forward too soon, the only way to go back is to press the next button until it gets back to the previous turn. They then have to reduce the combat turn by one. This is super tedious, and a "previous" button would be really nice to have.

**Comment by Azmoria** [comment]
Can this replace the roll button that's there? I don't think it currently has a function with reroll be seperate and rolling automatically happening. I agree that skipping a turn accidentally or just clicking next too soon is frustrating - I often just leave it wrong as it's too much as hassle as you say lol.

**Comment by CollinHerber** [comment]
> Can this replace the roll button that's there? I don't think it currently has a function with reroll being separate and rolling automatically happening. I agree that skipping a turn accidentally or just clicking next too soon is frustrating - I often just leave it wrong as it's too much as hassle as you say lol.
> 
> Happy to throw this together if no one else wants to/has time. Since I've been doing a bunch of CT stuff recently I don't think this would be difficult.

Additionally could use < and > characters to reduce size requirements
Going even a step further it would be nice to clean up text-buttons with FAB buttons https://m3.material.io/components/floating-action-button/overview - But really it's just for saving screen real-estate and looking clean in the processs
