### ISSUE TITLE
Alternate distance measurement options

### ISSUE THREAD

**Issue by smv620** [cyruzzo/AboveVTT#753]
Allow an option for DMs to set the ruler to 5e basic distance or set the ruler to use Euclidean distance.
5e basic is what is implemented currently in Fog.js :
`var distance = Math.max(Math.abs(snapPointXStart - snapPointXEnd), Math.abs(snapPointYStart - snapPointYEnd));`
`distance = Math.round(distance / gridSize);`

Euclidean distance would be (I think)
`var distance = Math.sqrt(Math.pow(snapPointXStart - snapPointXEnd, 2), Math.pow(snapPointYStart - snapPointYEnd, 2));`
`distance = Math.round(distance / gridSize);`

If the UI would be too complex for the DM to set it for other players, then perhaps holding the 'e' key while measuring the distance would display the Euclidean ruler instead?

P.S.  There is also a popular rule set that makes the diagonal distance such that every 2nd diagonal is counted extra. This is also called the 5-10-5 rule meaning the first diagonal is 5ft, the 2nd diagonal is 10ft, and the 3rd diagonal is back to 5ft again and repeat the sequence.  The number of diagonals in a single segment can be calculated as the difference of the long distance and the short distance between the x and y movements:

`var longDistance = Math.max(Math.abs(snapPointXStart - snapPointXEnd), Math.abs(snapPointYStart - snapPointYEnd));`
`longDistance = Math.round(distance / gridSize);`
`var shortDistance =  Math.min(Math.abs(snapPointXStart - snapPointXEnd), Math.abs(snapPointYStart - snapPointYEnd));`
`shortDistance =  Math.round(distance / gridSize);`
`// Diagonal movement is the difference of the long and short axis`
`var diagonalMovement = longDistance - shortDistance;`
`// I'm not sure where the square size comes from but I saw this in a sample line`
`var squareSize = window.CURRENT_SCENE_DATA.fpsq;`
`// the number of diagonal moves is the distance divided by the square size`
`var diagonalCount = Math.round(diagonalMovement / squareSize);`
`// only add an additional square of movement for every 2nd diagonal`
`var additionalSquares = Math.floor(diagonalCount / 2);`
`// multiply by the size of the square again (usually this is 5 ft)`
`var additionalDistance = additionalSquares * squareSize;`
`// add the additionalDistance to the original longDistance to get the final distance`
`var distance = longDistance + additionalDistance;`

Please forgive my errors in the example code.  I'm not a java programmer or I'd be happy to contribute myself.  While I've coded some in other languages, java is outside of my zone.  
**The players and I absolutely love AboveVTT!**  Thank you to everyone who contributes to this fantastic mod.

**Comment by vlaminck** [comment]
This has been done and rejected. I think it's worth revisiting since it gets requested so often. Here is the rejected PR for reference https://github.com/cyruzzo/AboveVTT/pull/581

**Comment by smv620** [comment]
Would a paid sponsorship drive this higher in the queue?  Venmo or Paypal options?

**Comment by Azmoria** [comment]
This has been in for awhile now - just cleaning up request issues that have been done already.
