### ISSUE TITLE
Add basic support for Universal VTT files

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#754]
These are just JSON files with the map as a base64 encoded string. Base64 encoded maps have been a problem in the past, but I think as long as we only accept the url where these files are hosted, it shouldn't be a problem. The problem with base64 encoded images is that they are really big strings that often exceed the max size of the websocket messages. Passing a url to a universal vtt file doesn't have that problem because it's just a url like any other image that we support.

### File extensions
These are the file extensions that I know of, but it might not even matter. If we know that it's a universal vtt file, we can just treat it as a `.json` file.
* `.dd2vtt`
* `.df2vtt`
* `.uvtt`

### JSON structure
There's more to the file than just this, but these are the only parts we care about
```
{
  "resolution": {
    "map_origin": {
      "x": 0,
      "y": 0
    },
    "map_size": {
      "x": 12,
      "y": 16
    },
    "pixels_per_grid": 120
  },
  "image": "<base64-encoded-image>"
}
```

### Creating a scene
During scene creation, we might be able to look at the file extension, but we might need a new option for "Universal VTT" similar to our "Is Video" option. We could then parse the JSON, and convert the `resolution` to our system, and save it the same way that we save all other maps.

### Rendering the image
We should pass the url to the file the same way that we pass urls to images. When we parse an image, we just have to check if it's a universal vtt file, then parse the JSON and render the base64 encoded image.

**Comment by Azmoria** [comment]
This has been working for a bit and haven't had any real big issues. Closing this as I think it's complete for now.
