### ISSUE TITLE
[Feature] Lock All Tokens on Scene

### ISSUE THREAD

**Issue by CollinHerber** [cyruzzo/AboveVTT#800]
When I saw the dynamic lightning video one of the things that came to mind was "Ohh I don't have to hide my tokens, they could just come into view when they are within the light" - However one problem that popped into my head was players going gung-ho and moving all around like crazy, so then came the idea of locking ALL tokens into place. Basically this would prevent all tokens from being moved by players. This would allow the DM to prevent any further changes happening and perhaps given time to catch up or do whatever they need to do for the scene.

Food for thought

**Comment by Azmoria** [comment]
This sounds similar to foundrys pause feature. I like that feature quite a bit myself.

**Comment by vlaminck** [comment]
I also really like the pause feature from foundry. It's really helpful when a player walks into a room or trap, and you want everything to stop while you describe the situation.
